import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "~/components/Header";
import SignUpForm from "~/components/SignUpForm";
import { ISignUp } from "~/common/validation/auth";
import { useCallback } from "react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const { mutateAsync } = api.auth.signUp.useMutation();

  const onSubmit = useCallback(
    async (data: ISignUp) => {
      const result = await mutateAsync(data);
      if (result.status === 201) {
        router.push("/");
      }
    },
    [mutateAsync, router]
  );
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center font-kanit tabular-nums">
        <Header />
        <section className="-z-10 mt-16 flex flex-auto flex-col bg-none py-10 px-0 font-kanit font-light leading-5 text-neutral-500">
          <section className="flex flex-auto flex-col">
            <main className="block flex-auto font-kanit font-light leading-5 text-neutral-500">
              <div className="mx-autoleading-5 px-6 text-neutral-500">
                <div className="my-0 mx-auto overflow-hidden rounded-[10px] bg-white leading-5 text-neutral-500">
                  <div className="relative flex h-64 grow flex-col items-start justify-center bg-zinc-300 bg-cover object-cover py-8 px-10 font-kanit font-light leading-5 text-white">
                    <div className=" z-10 bg-cover text-white">
                      <h2 className="text-3xl">ยินดีต้อนรับ</h2>
                      <p>เข้าสู่ระบบเพื่อใช้งาน</p>
                    </div>
                    <Image src={"/card-head.png"} fill alt="card-head" />
                  </div>
                  <div className="p-10 font-kanit font-light leading-5 text-neutral-500">
                    <SignUpForm onSubmit={onSubmit}/>
                  </div>
                </div>
              </div>
            </main>
          </section>
        </section>
      </main>
    </>
  );
};

export default Home;
